### ISSUE TITLE
gRPC

### ISSUE THREAD

**Issue by soyoungpark-me** [soyoungpark-me/study#1]
### 1. 기본 개념

![image](https://user-images.githubusercontent.com/17778171/226246860-449ff6b7-0431-47c4-b788-b26bc818c9f5.png)

- gRPC를 이용해, 클라이언트 어플리케이션이 서버 어플리케이션의 메소드를 더 간단하게 호출할 수 있다.
- 서비스 및 원격으로 호출될 수 있는 메소드를 파라미터와 리턴 타입과 함께 정의한다.
- 서버 측에서 해당 인터페이스를 구현하고, 클라이언트 호출을 다루기 위한 gRPC 서버를 구동한다.
- 클라이언트는 서버와 같은 메소드를 제공하는 `stub`을 가진다.
- 서버와 클라이언트는 서로 다른 언어와 환경으로 구현될 수 있다.
- gRPC는 구조화된 데이터를 직렬화하기 위한 오픈소스인 프로토콜 버퍼를 사용한다.

### 2. 서비스 정의

```proto
service HelloService {
  rpc SayHello (HelloRequest) returns (HelloResponse);
}

message HelloRequest {
  string greeting = 1;
}

message HelloResponse {
  string reply = 1;
}
```

다른 RPC 시스템들과 유사하게, gRPC는 서비스를 정의하는 것부터 시작한다.
- 파라미터 및 리턴 타입과 함께 원격에서 호출될 수 있는 메소드를 정의
- 서비스 인터페이스와 메시지 구조를 정의하기 위해 프로토콜 버퍼를 IDL (Interface Definition Language)으로 사용

서비스 메소드를 4개의 종류로 정의할 수 있다.

#### 1) Unary RPCs

```proto
rpc SayHello(HelloRequest) returns (HelloResponse);
```

- 클라이언트가 서버로 단건 요청을 보내고, 단건 응답을 받는다. (보통의 함수 호출과 같음)

#### 2) Server streaming RPCs

```proto
rpc LotsOfReplies(HelloRequest) returns (stream HelloResponse);
```

- 클라이언트가 서버로 요청을 보내면, 시퀀셜한 메시지를 읽어들일 수 있는 스트림을 응답으로 받는다.
- 클라이언트는 리턴된 스트리미 끝날 때까지 읽어들인다.
- gRPC는 개별 RPC 호출 내에서 메시지의 순서를 보장한다.

#### 3) Client streaming RPCs

```proto
rpc LotsOfGreetings(stream HelloRequest) returns (HelloResponse);
```

- 클라이언트가 제공되는 스트림을 통해 시퀀셜한 메시지들을 서버로 보낸다.
- 클라이언트가 메시지들을 보내는것을 완료하면, 서버가 메시지들을 읽어들이고 응답을 돌려줄 때까지 대기한다.
- gRPC는 개별 RPC 호출 내에서 메시지의 순서를 보장한다.

#### 4) Bidirectional streaming RPCs

```proto
rpc BidiHello(stream HelloRequest) returns (stream HelloResponse);
```

- 클라이언트와 서버 모두 read-write 스트림을 이용해 시퀀셜한 메시지를 보낸다.
- 두 스트림은 독립적으로 운용되고, 클라이언트와 서버는 원하는대로 순서를 매겨 읽고 쓸 수 있다.
ㄴ ex) 서버는 클라이언트의 모든 메시지를 받을 때까지 기다린 후에 응답을 쓰기 시작할 수 있다.
ㄴ ex) 메시지를 읽거나 쓰는 것을 교대로 진행할 수 있다.

### 3. API 사용

- `.proto` 파이르로 서비스 정의를 진행한 수, gRPC의 프로토콜 버퍼 컴파일러 플러그인을 통해 클라이언트와 서버의 코드를 생성할 수 있다.
- 서버 : 서비스로부터 정의된 메소드를 구현하고, gRPC 서버를 구동한다.
ㄴ gRPC가 들어오는 요청을 디코딩하고, 서비스 메소드를 실행시킨 뒤 응답을 인코딩한다.
- 클라이언트 : `stub`이라고 불리며 서비스와 같은 메소드를 구현하는 로컬 오브젝트를 가진다.
- 채널 : gRPC 채널은 호스트와 포트로 gPRC 서버와의 커넥션을 제공한다.
ㄴ 클라이언트의 `stub` 생성 시 사용되며, 채널은 `connected`와 `idle` 등의 상태를 가진다.

+) Synchronous vs. asynchronous
- Synchronous RPC는 서버로부터 응답을 받을 때까지 block 되도록 한다.
- gRPC API는 대부분의 언어에서 두 가지 기능을 모두 제공한다.

**Comment by soyoungpark-me** [comment]
## 사용 가이드

### 1. gRPC Interface 생성

#### 1-1) gPRC 서비스 정의 
- 우선 `proto` 파일을 생성해 gRPC 서비스, 메소드, request와 response 타입을 정의함
- [protocol buffers](https://protobuf.dev/overview/) 사용

```proto
syntax = "proto3";

// stub이 생성될 패키지의 경로, 미설정시 default proto 패키지 경로로 생성
option java_package = "com.example";

// 생성될 클래스명 정의 가능
option java_outer_classname = "CatalogProto";

// (default) false인 경우 CatalogProto.class 파일만 생성됨 
option java_multiple_files = true;

// service 정의
service CatalogService {
  rpc Catalog (CatalogRequest) returns (CatalogReply) {}
}

// protocol buffer의 메시지 타입 정의
message CatalogRequest {
  string name = 1;
}

message CatalogReply {
  int64 total = 1;
  repeated Catalog catalogs = 2;
}

message Catalog {
  int64 id = 1;
  string name = 2;
}
```

#### 1-2) build.gradle.kts 파일 수정
```kts
plugins {
    id("com.google.protobuf")
}

// 필요한 의존성 추가
dependencies {
    api("io.grpc:grpc-protobuf")
    api("io.grpc:grpc-stub")
    api("io.grpc:grpc-kotlin-stub")
    api("com.google.protobuf:protobuf-kotlin")
}

// protobuf 및 stub 클래스 생성
protobuf {
    protoc {
        // protobuf compiler
        artifact = "com.google.protobuf:protoc:${rootProject.ext["protobufVersion"]}"
    }

    plugins {
        id("grpc") {
            artifact = "io.grpc:protoc-gen-grpc-java:${rootProject.ext["grpcVersion"]}"
        }
        id("grpckt") {
            artifact = "io.grpc:protoc-gen-grpc-kotlin:${rootProject.ext["grpcKotlinVersion"]}:jdk8@jar"
        }
    }
    generateProtoTasks {
        all().forEach {
            it.plugins {
                id("grpc")
                id("grpckt")
            }
            it.builtins {
                id("kotlin")
            }
        }
    }
}
```

#### 1-3) 빌드해 stub 클래스 생성

![image](https://user-images.githubusercontent.com/17778171/225596689-8f3eb239-05d2-449e-9778-0771c602555c.png)

___

### 2. gRPC 서버 구동

#### 1-1) build.gradle.kts 수정
```kts
dependencies {
    implementation(project(":libs:grpc")) // 1번에서 빌드한 stub 포함
    implementation("io.grpc:grpc-netty")
}
```

#### 1-2) service 클래스 구현
```kt
// 1-3을 통해 생성된 클래스 사용
import com.example.CatalogReply
import com.example.CatalogRequest
import com.example.CatalogServiceGrpcKt
import com.example.catalogReply

class CatalogGrpcService(private val port: Int) {
    // `io.grpc.Server` 구동
    val server: Server = ServerBuilder
        .forPort(port)
        .addService(CatalogService())
        .build()

    fun start() {
        server.start()
        Runtime.getRuntime().addShutdownHook(
            Thread {
                this@CatalogGrpcService.stop()
            }
        )
    }

    private fun stop() {
        server.shutdown()
    }

    fun blockUntilShutdown() {
        server.awaitTermination()
    }

    // CatalogService 내부 동작 구현
    internal class CatalogService(
        private val catalogRepository: CatalogRepository = CatalogRepository()
    ) : CatalogServiceGrpcKt.CatalogServiceCoroutineImplBase() {
        // proto 파일에서 정의한 rpc 함수 구현
        override suspend fun catalog(request: CatalogRequest): CatalogReply {
            val response = catalogRepository.catalogs()
            return catalogReply { // this: CatalogReplyKt.Dsl
                // 내부 동작 구현
            }
        }
    }
}
```

___

### 3. gRPC 클라이언트 구현

#### 3-1) build.gradle.kts 수정
```kts
dependencies {
    implementation(project(":libs:grpc")) // 1번에서 빌드한 stub 포함
    implementation("io.grpc:grpc-okhttp")
}
```

#### 3-2) stub을 통해 서버 호출
```kt
// 1-3을 통해 생성된 클래스 사용
import com.example.CatalogServiceGrpc
import com.example.CatalogServiceGrpcKt
import com.example.catalogRequest

// stub 통신을 위한 채널 생성 (2번에서 생성한 gRPC 서버와 통신)
private val channel = ManagedChannelBuilder.forTarget("${clientProperties.host}:${clientProperties.port}")
        .usePlaintext()
        .build()

// 동기식 stub 생성
private val stub = CatalogServiceGrpc.newBlockingStub(channel)

// coroutine stub 생성 (사용 시 suspend로 함수를 정의해야 함)
private val coroutineStub = CatalogServiceGrpcKt.CatalogServiceCoroutineStub(channel)
```

**Comment by soyoungpark-me** [comment]
## 인증

SSL\TLS 및 구글 토큰 기반 인증, 또는 직접 인증 시스템을 구현해 추가할 수 있다.
간단한 인증 API를 통해 모든 필요한 인증 정보를 채널 생성 시나 함수 호출 시에 `Credentials`으로 제공할 수 있다.

- **SSL/TLS** : SSL/TLS로 서버를 인증하고 서버 간에 교환되는 모든 데이터를 암호화 할 수 있다. 
- **Token-based authentication** : 통상적인 방법으로, 인증에 기반한 메타데이터를 request 및 response에 추가한다.
ㄴ 일반적으로 이 메커니즘은 SSL/TLS와 함께 사용되어야 한다.
ㄴ 대부분의 gRPC 구현체는 암호화되지 않은 채널에서 인증 정보를 보낼 수 없게 되어있다.
- **ALTS** : GCP 위에서 구동되는 어플리케이션의 경우 사용할 수 있는 시스템
ㄴ [ALTS](https://cloud.google.com/docs/security/encryption-in-transit/application-layer-transport-security?hl=ko) : Google이 개발한 상호 인증 및 전송 암호화 시스템으로, 일반적으로 Google 인프라 내에서 리모트 프로시져 콜(RPC) 통신의 보안을 유지하는 데 사용

**Comment by soyoungpark-me** [comment]
## 오류 처리
gRPC 요청의 경우 성공 시 서버는 OK status를 반환한다.

![image](https://user-images.githubusercontent.com/17778171/227125870-10c4080f-9f45-4be0-bad0-e49cd6cf76ff.png)

만약 에러가 발생할 경우, gRPC는 선택적으로 추가할 수 있는 오류 메시지와 함께 오류 상태 코드를 대신 반환한다.
+) 테스트 코드에서 강제로 `RuntimeException` 발생 시 다음과 같이 반환된다.

![image](https://user-images.githubusercontent.com/17778171/227127250-dd95da56-e17c-493c-a8df-c46204cbafea.png)

```sh
// 클라이언트 stub에서 호출 시
io.grpc.StatusRuntimeException: UNKNOWN
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:271) ~[grpc-stub-1.47.0.jar:1.47.0]
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:252) ~[grpc-stub-1.47.0.jar:1.47.0]
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:165) ~[grpc-stub-1.47.0.jar:1.47.0]
	at com.example.CatalogServiceGrpc$CatalogServiceBlockingStub.catalog(CatalogServiceGrpc.java:157) ~[main/:na]
```

\+ 작성중 ..

**Comment by soyoungpark-me** [comment]
## gRPC 서버 인터셉터

### [ServerInterceptor](https://github.com/grpc/grpc-java/blob/master/api/src/main/java/io/grpc/ServerInterceptor.java)

> Interface for intercepting incoming calls before that are dispatched by ServerCallHandler

- 인터셉터는 이전 스레드를 먼저 완료하지 않고 n개 스레드에 의해 여러 {@ServerCall}에 대해 호출될 수 있음
- 보통 다음 목적을 위해 사용됨
  - Enforcing valid authentication credentials
  - Logging and monitoring call behavior
  - Delegating calls to other servers

```kt
/**
 * {@next: ServerCallHandler}에 의한 {@ServerCall} 발송을 차단함
* 구현에서 예외가 발생하면 {@call}이 오류와 함께 종료됨
*/
<ReqT, RespT> ServerCall.Listener<ReqT> interceptCall(
    call: ServerCall<ReqT, RespT>, // 서버가 반환한 응답 메시지를 받을 객체
    headers: Metadata, // 통신 메타데이터를 가지는 객체로, 커스터메이징 가능
    next: ServerCallHandler<ReqT, RespT> // 인터셉터 체인의 다음 처리를 수행할 객체
)
```

### [ServerCallHandler](https://github.com/grpc/grpc-java/blob/master/api/src/main/java/io/grpc/ServerCallHandler.java)

> Interface to initiate processing of incoming remote calls

- {@Server}가 서비스 메서드를 호출할 수 있도록 함

```java
/**
 * 들어오는 call의 비동기 처리를 시작하며, null이 아닌 리스너를 반환함
 */
ServerCall.Listener<RequestT> startCall(
      ServerCall<RequestT, ResponseT> call, // 클라이언트에게 응답해줄 객체
      Metadata headers // 클라이언트로부터 받은 요청 헤더 정보
)
```

### [ServerCall](https://github.com/grpc/grpc-java/blob/master/api/src/main/java/io/grpc/ServerCall.java)

> Helpers for implementing a gRPC server based on a Kotlin coroutine implementation.

- 클라이언트로부터 받은 단건 call을 캡슐화하는 API
- unary 요청이 가장 흔하게 사용되지만, 다수의 request와 response의 스트림으로 요청될 수도 있다.
- 헤더는 반드시 메시지 이전에, close 되기 전에 전달되어야 한다.

```kt
/**
 * ServerCall.Listener.onMessage(object)로 전달되기 위해 호출되는 메시지들 수 만큼 요청함
 * {@numMessages}가 전달되면, 다시 이 메소드가 호출되기 전까지 request 메시지를 전달받지 않음
 * 외부 동기화 없이 여러 스레드에서 호출되어도 안전함
 * 
 * → 서버에서 클라이언트로의 flow-control을 위해 back-pressure를 주어야 할 때 사용됨
 */
override fun request(numMessages: Int)

/**
 * response 메시지를 보내기 이전에 헤더 메타데이터를 보냄
 * 한 번만 호출할 수 있으며 {@sendMessage}, {@close} 호출 후에는 호출할 수 없음
 * {@Metadata}는 스레드로부터 안전하지 않으므로 caller는 이 시점 이후에 {@headers}에 액세스하면 안됨
 */
override fun sendHeaders(headers: Metadata?)

/**
 * 응답 메시지를 보냄
 * streaming call일 경우 응답 메시지는 여러개가 될 수 있음
 */
override fun sendMessage(message: RespT)

/**
 * 제공된 상태 (status)와 함께 요청을 종료해, 호출된 이후엔 송신이나 수신이 발생하지 않게 됨
 * {@Status#isOk}가 false이면 호출이 실패한 것
 * 호출 성공 시 {@status}와 관계없이 {@Listener#onComplete}, 실패 시 {@Listener#onCancel} 메소드가 호출됨
 * {@Metadata}는 스레드로부터 안전하지 않으므로 caller는 이 시점 이후에 {@trailers}에 액세스하면 안됨
 *
 * call이 실제로 완료/종료된 시점을 알고 싶다면 이 메소드 대신 {@Listener#onComplete} 또는 {@Listener#onCancel}을 사용해야 함
 * +) 이 메서드는 {@Listener#onCancel} 메소드가 호출될 때 반드시 호출되는 것은 아님
 */
override fun close(status: Status?, trailers: Metadata?)

/**
 * call이 취소되고 서버가 리소스 절약을 위해 처리를 중단할 경우 true를 반환함
 * 취소는 시간 초과, 클라이언트의 명시적 취소, 네트워크 오류 등으로 인해 발생할 수 있음
 */
override fun isCancelled(): Boolean

/**
 * call을 위한 MethodDescriptor
 */
override fun getMethodDescriptor(): MethodDescriptor<ReqT, RespT>
```

#### ServerCall.Listener

- 들어오는 RPC 메시지를 사용하기 위한 콜백
- 컨텍스트는 call이 완료 되기 전, half close 상태의 모든 메시지들보다 앞서 수신되는 것이 보장됨

```kt
/**
 * request 메시지가 수신됨
 * 스트리밍 호출의 경우 n개의 request 메시지가 수신될 수 있음
 */
public void onMessage(ReqT message)

/**
 * 클라이언트가 모든 메시지 전송을 완료함, call은 취소될 수 있는 상태
 */
public void onHalfClose()

/**
 * call이 취소되면 서버가 리소스 절약을 위해 처리를 중단함
 * 취소는 시간 초과, 클라이언트의 명시적 취소, 네트워크 오류 등으로 인해 발생할 수 있음
 * +) 추가 callback이 발생하지 않게 됨
 */
public void onCancel()

/**
 * 호출이 완료된 것으로 간주되며 {@onCancel} 메소드가 호출되지 않도록 보장함
 * 클라이언트가 모든 메시지를 수신했다고 보장할 수는 없음
 */
public void onComplete()

/**
 * 호출이 내부적으로 과도한 버퍼링을 요구하지 않고 이제 {@sendMessage} 메소드로 추가 메시지를 보낼 수 있음을 의미
 */
public void onReady()
```

#### ForwardingServerCall.SimpleForwardingServerCall
- ServerCall의 경우 모든 메소드를 오버라이딩해줘야 함
- 특정 메소드만 오버라이딩 하고 싶을 경우 사용

**Comment by soyoungpark-me** [comment]
## gRPC 서버 인터셉터

### [ServerInterceptor](https://github.com/grpc/grpc-java/blob/master/api/src/main/java/io/grpc/ServerInterceptor.java)

> Interface for intercepting incoming calls before that are dispatched by ServerCallHandler

- 인터셉터는 이전 스레드를 먼저 완료하지 않고 n개 스레드에 의해 여러 {@ServerCall}에 대해 호출될 수 있음
- 보통 다음 목적을 위해 사용됨
  - Enforcing valid authentication credentials
  - Logging and monitoring call behavior
  - Delegating calls to other servers

```kt
/**
 * {@next: ServerCallHandler}에 의한 {@ServerCall} 발송을 차단함
* 구현에서 예외가 발생하면 {@call}이 오류와 함께 종료됨
*/
<ReqT, RespT> ServerCall.Listener<ReqT> interceptCall(
    call: ServerCall<ReqT, RespT>, // 서버가 반환한 응답 메시지를 받을 객체
    headers: Metadata, // 통신 메타데이터를 가지는 객체로, 커스터메이징 가능
    next: ServerCallHandler<ReqT, RespT> // 인터셉터 체인의 다음 처리를 수행할 객체
)
```

### [ServerCallHandler](https://github.com/grpc/grpc-java/blob/master/api/src/main/java/io/grpc/ServerCallHandler.java)

> Interface to initiate processing of incoming remote calls

- {@Server}가 서비스 메서드를 호출할 수 있도록 함

```java
/**
 * 들어오는 call의 비동기 처리를 시작하며, null이 아닌 리스너를 반환함
 */
ServerCall.Listener<RequestT> startCall(
      ServerCall<RequestT, ResponseT> call, // 클라이언트에게 응답해줄 객체
      Metadata headers // 클라이언트로부터 받은 요청 헤더 정보
)
```

### [ServerCall](https://github.com/grpc/grpc-java/blob/master/api/src/main/java/io/grpc/ServerCall.java)

> Helpers for implementing a gRPC server based on a Kotlin coroutine implementation.

- 클라이언트로부터 받은 단건 call을 캡슐화하는 API
- unary 요청이 가장 흔하게 사용되지만, 다수의 request와 response의 스트림으로 요청될 수도 있다.
- 헤더는 반드시 메시지 이전에, close 되기 전에 전달되어야 한다.

```kt
/**
 * ServerCall.Listener.onMessage(object)로 전달되기 위해 호출되는 메시지들 수 만큼 요청함
 * {@numMessages}가 전달되면, 다시 이 메소드가 호출되기 전까지 request 메시지를 전달받지 않음
 * 외부 동기화 없이 여러 스레드에서 호출되어도 안전함
 * 
 * → 서버에서 클라이언트로의 flow-control을 위해 back-pressure를 주어야 할 때 사용됨
 */
override fun request(numMessages: Int)

/**
 * response 메시지를 보내기 이전에 헤더 메타데이터를 보냄
 * 한 번만 호출할 수 있으며 {@sendMessage}, {@close} 호출 후에는 호출할 수 없음
 * {@Metadata}는 스레드로부터 안전하지 않으므로 caller는 이 시점 이후에 {@headers}에 액세스하면 안됨
 */
override fun sendHeaders(headers: Metadata?)

/**
 * 응답 메시지를 보냄
 * streaming call일 경우 응답 메시지는 여러개가 될 수 있음
 */
override fun sendMessage(message: RespT)

/**
 * 제공된 상태 (status)와 함께 요청을 종료해, 호출된 이후엔 송신이나 수신이 발생하지 않게 됨
 * {@Status#isOk}가 false이면 호출이 실패한 것
 * 호출 성공 시 {@status}와 관계없이 {@Listener#onComplete}, 실패 시 {@Listener#onCancel} 메소드가 호출됨
 * {@Metadata}는 스레드로부터 안전하지 않으므로 caller는 이 시점 이후에 {@trailers}에 액세스하면 안됨
 *
 * call이 실제로 완료/종료된 시점을 알고 싶다면 이 메소드 대신 {@Listener#onComplete} 또는 {@Listener#onCancel}을 사용해야 함
 * +) 이 메서드는 {@Listener#onCancel} 메소드가 호출될 때 반드시 호출되는 것은 아님
 */
override fun close(status: Status?, trailers: Metadata?)

/**
 * call이 취소되고 서버가 리소스 절약을 위해 처리를 중단할 경우 true를 반환함
 * 취소는 시간 초과, 클라이언트의 명시적 취소, 네트워크 오류 등으로 인해 발생할 수 있음
 */
override fun isCancelled(): Boolean

/**
 * call을 위한 MethodDescriptor
 */
override fun getMethodDescriptor(): MethodDescriptor<ReqT, RespT>
```

#### ServerCall.Listener

- 들어오는 RPC 메시지를 사용하기 위한 콜백
- 컨텍스트는 call이 완료 되기 전, half close 상태의 모든 메시지들보다 앞서 수신되는 것이 보장됨

```kt
/**
 * request 메시지가 수신됨
 * 스트리밍 호출의 경우 n개의 request 메시지가 수신될 수 있음
 */
public void onMessage(ReqT message)

/**
 * 클라이언트가 모든 메시지 전송을 완료함, call은 취소될 수 있는 상태
 */
public void onHalfClose()

/**
 * call이 취소되면 서버가 리소스 절약을 위해 처리를 중단함
 * 취소는 시간 초과, 클라이언트의 명시적 취소, 네트워크 오류 등으로 인해 발생할 수 있음
 * +) 추가 callback이 발생하지 않게 됨
 */
public void onCancel()

/**
 * 호출이 완료된 것으로 간주되며 {@onCancel} 메소드가 호출되지 않도록 보장함
 * 클라이언트가 모든 메시지를 수신했다고 보장할 수는 없음
 */
public void onComplete()

/**
 * 호출이 내부적으로 과도한 버퍼링을 요구하지 않고 이제 {@sendMessage} 메소드로 추가 메시지를 보낼 수 있음을 의미
 */
public void onReady()
```

#### ForwardingServerCall.SimpleForwardingServerCall
- ServerCall의 경우 모든 메소드를 오버라이딩해줘야 함
- 특정 메소드만 오버라이딩 하고 싶을 경우 사용

**Comment by soyoungpark-me** [comment]
## 서버 오류 처리
### 1. gRPC 요청 성공

- 서버는 OK status를 반환한다.

  ![image](https://user-images.githubusercontent.com/17778171/227125870-10c4080f-9f45-4be0-bad0-e49cd6cf76ff.png)

만약 에러가 발생할 경우, gRPC는 선택적으로 추가할 수 있는 오류 메시지와 함께 오류 상태 코드를 대신 반환한다.

### 2. gRPC 요청 실패 - 기본 결과

- 테스트 코드에서 강제로 `RuntimeException` 발생 시 다음과 같이 반환된다.

  ![image](https://user-images.githubusercontent.com/17778171/227127250-dd95da56-e17c-493c-a8df-c46204cbafea.png)

  ```sh
  // 클라이언트 stub에서 호출 시
  io.grpc.StatusRuntimeException: UNKNOWN
      at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:271) ~[grpc-stub-1.47.0.jar:1.47.0]
      at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:252) ~[grpc-stub-1.47.0.jar:1.47.0]
      at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:165) ~[grpc-stub-1.47.0.jar:1.47.0]
      at com.example.CatalogServiceGrpc$CatalogServiceBlockingStub.catalog(CatalogServiceGrpc.java:157) ~[main/:na]
  ```

### 2. gRPC 요청 실패 - 세부 정보 추가

- 서버 측에서 내부적으로 발생한 Exception 별로 다른 status 코드를 반환하기 위해서 `ServerInterceptor` 구현이 필요하다.
ㄴ **[참고]** https://github.com/grpc/grpc-kotlin/issues/141

-  Protocol buffers의 [Richer error model](https://cloud.google.com/apis/design/errors?hl=ko#error_info)을 사용해 자세한 오류 정보를 클라이언트로 보내줄 수 있다

```kt
{
  "error": {
    "code": 400,
    "message": "API key not valid. Please pass a valid API key.",
    "status": "INVALID_ARGUMENT",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.ErrorInfo",
        "reason": "API_KEY_INVALID",
        "domain": "googleapis.com",
        "metadata": {
          "service": "translate.googleapis.com"
        }
      }
    ]
  }
}
```

- ServerInterceptor + Richer error model 적용 결과
  
  ![image](https://user-images.githubusercontent.com/17778171/227460742-03323509-e53e-4daa-9ef3-377d4367513c.png)

  ```sh
  // 클라이언트 stub에서 호출 시
  io.grpc.StatusRuntimeException: INVALID_ARGUMENT: 
      at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:271) ~[grpc-stub-1.47.0.jar:1.47.0]
      at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:252) ~[grpc-stub-1.47.0.jar:1.47.0]
      at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:165) ~[grpc-stub-1.47.0.jar:1.47.0]
	at com.example.CatalogServiceGrpc$CatalogServiceBlockingStub.catalog(CatalogServiceGrpc.java:157) ~[main/:na]
  ```
